### PR TITLE
Footer Overflow fixed.

### PR DESCRIPTION
**Pull request by sarthakastic**

### CODE REVIEW

**Comment by dbazhenov** [comment]
Hi, I think the package-lock.json file is redundant, please delete it, or explain the purpose.

**Comment by sarthakastic** [comment]
Yeah, it was redundant I removed it. pls, review it once again.

**Review by dbazhenov — APPROVED** [review]
Thank you so much for your contribution.

**Comment by sarthakastic** [comment]
Thanks for your constant support and guidance.

**Pull request merged**
